
这是一个施密特正交化方法的测试文档。

In [2]:
import numpy as np

A = np.array([[2,-1,-1,1],[-1,2,1,-1],[-1,1,2,-1],[1,-1,-1,2]])

eigen=np.linalg.eig(A)[0]
P_normal=np.linalg.eig(A)[1]*1


print(eigen)
print(P_normal)
print(np.linalg.inv(P_normal)@A@P_normal)

[1. 5. 1. 1.]
[[-0.8660254   0.5        -0.0478617   0.04830582]
 [-0.28867513 -0.5         0.43075529 -0.69238343]
 [-0.28867513 -0.5         0.35129375  0.71960202]
 [ 0.28867513  0.5         0.82991074 -0.02108723]]
[[ 1.00000000e+00 -8.18789481e-16  8.32667268e-17 -3.46944695e-17]
 [-6.66133815e-16  5.00000000e+00 -8.88178420e-16  2.56739074e-16]
 [-1.11022302e-16  1.16573418e-15  1.00000000e+00 -5.89805982e-17]
 [ 3.81639165e-17 -1.86656246e-15 -4.16333634e-17  1.00000000e+00]]


易得出结论:
* 实对称矩阵对角化所选取的过渡矩阵不一定需要进行正交单位化
* 对过渡矩阵进行正交单位化是为了便于计算。

这里贴一段ChatGPT写的Schmidt正交化方法。

In [5]:
import numpy as np


def schmidt_orthogonalization(matrix):
    """
    Schmidt orthogonalization of a given matrix using NumPy.
    """
    # Get the number of rows and columns of the matrix.
    rows, cols = matrix.shape

    # Initialize an empty matrix to hold the orthogonal vectors.
    orthogonal_matrix = np.zeros((rows, cols))

    # Iterate over each column of the original matrix.
    for i in range(cols):
        # Take the current column as the initial orthogonal vector.
        orthogonal_vector = matrix[:, i]

        # Subtract the projections of previous orthogonal vectors from the current vector.
        for j in range(i):
            orthogonal_vector -= np.dot(matrix[:, i],
                                        orthogonal_matrix[:, j]) * orthogonal_matrix[:, j]

        # Normalize the resulting orthogonal vector.
        orthogonal_vector /= np.linalg.norm(orthogonal_vector)

        # Add the orthogonal vector to the orthogonal matrix.
        orthogonal_matrix[:, i] = orthogonal_vector

    # Return the orthogonal matrix.
    return orthogonal_matrix


print(schmidt_orthogonalization(P_normal))

[[-8.66025404e-01  5.00000000e-01 -1.38990301e-17 -3.56850592e-17]
 [-2.88675135e-01 -5.00000000e-01  4.47392951e-01 -6.83012601e-01]
 [-2.88675135e-01 -5.00000000e-01  3.67809788e-01  7.28959962e-01]
 [ 2.88675135e-01  5.00000000e-01  8.15202740e-01  4.59473606e-02]]
