
这是一个施密特正交化方法的测试文档。

In [2]:
import numpy as np

A = np.array([[2,-1,-1,1],[-1,2,1,-1],[-1,1,2,-1],[1,-1,-1,2]])

eigen=np.linalg.eig(A)[0]
P_normal=np.linalg.eig(A)[1]*1


print(eigen)
print(P_normal)
print(np.linalg.inv(P_normal)@A@P_normal)

[1. 5. 1. 1.]
[[-0.8660254  -0.5        -0.18045389  0.09837421]
 [-0.28867513  0.5         0.73842321 -0.32999351]
 [-0.28867513  0.5        -0.45943855  0.84254576]
 [ 0.28867513 -0.5         0.45943855  0.41417804]]
[[ 1.00000000e+00 -4.59811972e-16 -6.68984864e-17 -3.46362729e-19]
 [-6.76714180e-16  5.00000000e+00 -3.78835386e-16 -3.71179514e-16]
 [ 1.27103093e-17 -1.22735999e-17  1.00000000e+00  4.92980278e-17]
 [-2.13002570e-18 -1.13398294e-17 -2.26939630e-17  1.00000000e+00]]


易得出结论:
* 实对称矩阵对角化所选取的过渡矩阵不一定需要进行正交单位化
* 对过渡矩阵进行正交单位化是为了便于计算。